# Generated by Django 5.1.4 on 2025-05-19 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_descuentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='fecha_registro_descuento',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
