# Generated by Django 5.1.4 on 2026-02-21 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_descuentos_fecha_registro_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='fecha_registro_descuento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
