"""
Django settings for pl_salon project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY',default='your secret key')



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['*']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# settings.py
LOGIN_URL = '/'  # Ruta a tu vista de inicio de sesión

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'tailwind',
    'theme',

    
]

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middlewares.SessionTimeoutMiddleware',
    
]

ROOT_URLCONF = 'pl_salon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "theme"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'pl_salon.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://USER:PASSWORD@HOST:5032/db_pl_salon',
        conn_max_age=600
    )
    
    
    #     'default':  {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'db_pl_salon',
    #     'USER':'postgres',
    #     'PASSWORD':'Ronald2121/24-',
    #     'HOST':'localhost',
    #     'PORT':'5432',
    # }


}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/El_Salvador'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'

# Directorios adicionales para buscar archivos estáticos en desarrollo
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configuración de archivos estáticos para producción
DEBUG = os.getenv('DEBUG', 'False') == 'True'  # Lee DEBUG desde variables de entorno

if not DEBUG:
    STATIC_ROOT = BASE_DIR / "staticfiles"  # Ruta donde se recopilarán los archivos estáticos
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATIC_ROOT = None  # En desarrollo no se usa `collectstatic`
    
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NPM_BIN_PATH = 'npm.cmd'
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

#configuracion para sesiones basaas en cookies
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Puedes usar 'cache' si prefieres almacenamiento en memoria

# Configurar el tiempo de expiración (10 minutos = 600 segundos)
SESSION_COOKIE_AGE = 600  # Tiempo en segundos antes de que expire la sesión

# Expulsar al usuario después de la expiración de la sesión
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Cierra la sesión al cerrar el navegador
SESSION_SAVE_EVERY_REQUEST = True  # Renueva la sesión con cada solicitud


